/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppMenu: typeof import('./src/components/layout/AppMenu.vue')['default']
    AppMenuItem: typeof import('./src/components/layout/AppMenuItem.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    Calendar: typeof import('primevue/calendar')['default']
    Card: typeof import('primevue/card')['default']
    Carousel: typeof import('primevue/carousel')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    Inplace: typeof import('primevue/inplace')['default']
    InputMask: typeof import('primevue/inputmask')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    JDataTable: typeof import('./src/components/data/JDataTable.vue')['default']
    JDropdown: typeof import('./src/components/form/JDropdown.vue')['default']
    JInputGroup: typeof import('./src/components/form/JInputGroup.vue')['default']
    JInputNumber: typeof import('./src/components/form/JInputNumber.vue')['default']
    JInputText: typeof import('./src/components/form/JInputText.vue')['default']
    JNaverMap: typeof import('./src/components/map/JNaverMap.vue')['default']
    JNaverMapPanel: typeof import('./src/components/map/JNaverMapPanel.vue')['default']
    JPassword: typeof import('./src/components/form/JPassword.vue')['default']
    LayoutFooter: typeof import('./src/components/layout/LayoutFooter.vue')['default']
    LayoutHeader: typeof import('./src/components/layout/LayoutHeader.vue')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    OverlayPanel: typeof import('primevue/overlaypanel')['default']
    Password: typeof import('primevue/password')['default']
    Rating: typeof import('primevue/rating')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Slider: typeof import('primevue/slider')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabView: typeof import('primevue/tabview')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    ToggleButton: typeof import('primevue/togglebutton')['default']
  }
}
