### 토큰 체크
POST {{hostname}}/api/token/check
Authorization: Bearer {{tokenAdmin}}
content-type: application/json

{
  "accessToken": "eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJpZCI6MSwidXNlcklkIjoiYWRtaW4iLCJzdWIiOiJhZG1pbiIsImlhdCI6MTcwMjczMTc1MywiZXhwIjoxNzAyOTA0NTUzfQ.Jc-pqLS9nw-CmJcZFh3Dyh3rSqewgk41EoKEm9bh_ms",
  "refreshToken": "eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJpZCI6MSwiYWNjZXNzVG9rZW4iOiJleUpoYkdjaU9pSklVekkxTmlKOS5leUp5YjJ4bElqb2lRVVJOU1U0aUxDSnBaQ0k2TVN3aWRYTmxja2xrSWpvaVlXUnRhVzRpTENKemRXSWlPaUpoWkcxcGJpSXNJbWxoZENJNk1UY3dNamN6TVRjMU15d2laWGh3SWpveE56QXlPVEEwTlRVemZRLkpjLXBxTFM5bnctQ21KY1pGaDNEeWgzclNxZXdnazQxRW9LRW05YmhfbXMiLCJ1c2VySWQiOiJhZG1pbiIsInN1YiI6ImFkbWluIiwiaWF0IjoxNzAyNzMxNzUzLCJleHAiOjE3MDI5OTA5NTN9.NEykRSu8cVNyaSrBLoz952TNQJVwAktzZWDPK4MQKUM"
}